# 상품을 구매한 회원 비율 구하기
# 프로그래머스 (unknown)
# 문제 링크: https://school.programmers.co.kr/learn/courses/30/lessons/131534
# 작성자: 김민수
# 작성일: 2026. 01. 19. 09:40:07

-- 코드를 입력하세요
# 2021년 가입한 전체 회원
WITH USER2021 AS 
(SELECT USER_ID
FROM USER_INFO
WHERE YEAR(JOINED) = 2021)

SELECT 
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM USER2021),1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT * FROM USER2021)
GROUP BY 
    YEAR(SALES_DATE),
    MONTH(SALES_DATE)
ORDER BY YEAR, MONTH